Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,6 +9,11 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     steps:
+      - name: Add GitHub to known hosts
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+
       - name: executing remote ssh commands using ssh key
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -17,7 +22,9 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           script: |
             whoami
-            mkdir testq
+            if [ ! -d "testq" ]; then
+              mkdir testq
+            fi
             cd testq
-            git clone git@github.com:u21513768/testrepo.git
+            git clone git@github.com:u21513768/testrepo.git || echo "Repository already exists or failed to clone"
             echo 'Deployment successful'
